CREATE TABLE books (
	id BIGINT NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	author VARCHAR(100) NOT NULL,
	amount INT(20) NOT NULL,
	gender VARCHAR(30) NOT NULL,
	format VARCHAR(30) NOT NULL,
	public_date VARCHAR(20) NOT NULL,
	description VARCHAR(200) NOT NULL,
PRIMARY KEY(id)
);